version: '3.8'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parser
    volumes:
      - /opt/docker_containers/parser/result/:/app/result/
    restart: no